[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://polyscribe.fr/*"
  to = "https://www.polyscribe.fr/:splat"
  statues = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200